services:
  - type: web
    name: my-django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn weather_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: weather_project.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
    staticPublishPath: staticfiles
